//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreatedFiles = new HashSet<File>();
            this.Purchases = new HashSet<Purchase>();
            this.OwnedFiles = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<File> CreatedFiles { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<File> OwnedFiles { get; set; }
    }
}
